require_relative '../node_modules/react-native/scripts/react_native_pods'
require_relative '../node_modules/@react-native-community/cli-platform-ios/native_modules'

platform :ios, '11.0'

target 'MClub' do
  config = use_native_modules!

  use_react_native!(:path => config["reactNativePath"])

  pod 'Interactable', :path => '../node_modules/react-native-interactable'

  pod 'RNDateTimePicker', :path => '../node_modules/@react-native-community/datetimepicker'

  pod 'react-native-image-picker', :path => '../node_modules/react-native-image-picker'

  pod 'rn-fetch-blob', :path => '../node_modules/rn-fetch-blob'

  pod 'react-native-date-picker', :path => '../node_modules/react-native-date-picker'

  pod 'RNSVG', :path => '../node_modules/react-native-svg'

  pod 'react-native-camera', :path => '../node_modules/react-native-camera'

  permissions_path = '../node_modules/react-native-permissions/ios'
  pod 'Permission-Camera', :path => "#{permissions_path}/Camera"

  pod 'RNPermissions', :path => '../node_modules/react-native-permissions'

  target 'MClubTests' do
    inherit! :complete
    # Pods for testing
  end

  # Enables Flipper.
  #
  # Note that if you have use_frameworks! enabled, Flipper will not work and
  # you should disable these next few lines.
  use_flipper!({ 'Flipper' => '0.87.0', 'Flipper-Folly' => '2.5.3', 'Flipper-RSocket' => '1.3.1' })
  post_install do |installer|
    flipper_post_install(installer)
  end
end

target 'MClub-tvOS' do
  # Pods for MClub-tvOS

  target 'MClub-tvOSTests' do
    inherit! :search_paths
    # Pods for testing
  end
end

target 'OneSignalNotificationServiceExtension' do
  pod 'OneSignal', '>= 2.0', '< 4.0'
end
