require_relative '../node_modules/react-native/scripts/react_native_pods'
require_relative '../node_modules/@react-native-community/cli-platform-ios/native_modules'

platform :ios, '11.0'

target 'MClub' do
  config = use_native_modules!

  use_react_native!(:path => config["reactNativePath"])

  pod 'Interactable', :path => '../node_modules/react-native-interactable'

  pod 'RNDateTimePicker', :path => '../node_modules/@react-native-community/datetimepicker'

  pod 'react-native-image-picker', :path => '../node_modules/react-native-image-picker'

  pod 'rn-fetch-blob', :path => '../node_modules/rn-fetch-blob'

  target 'MClubTests' do
    inherit! :complete
    # Pods for testing
  end

  # Enables Flipper.
  #
  # Note that if you have use_frameworks! enabled, Flipper will not work and
  # you should disable these next few lines.
  use_flipper!
  post_install do |installer|
    flipper_post_install(installer)
  end
end

target 'MClub-tvOS' do
  # Pods for MClub-tvOS

  target 'MClub-tvOSTests' do
    inherit! :search_paths
    # Pods for testing
  end
end
