export const screens = {
  HOME: "HOME",
  TAB_ACCOUNT: "TAB_ACCOUNT",
  TAB_NAVIGATE: "TAB_NAVIGATE",
  TAB_NOTIFICATION: "TAB_NOTIFICATION",
  TAB_TASK: "TAB_TASK",
  LOGIN: "LOGIN",
  SIGNUP: "SIGNUP",
  MEMBER: "MEMBER",
  SPINNER: "SPINNER",
  DEPARTMENT: "DEPARTMENT",
  POSITION: "POSITION",
};

export const modals = {
  SELECT_MODAL: "SELECT_MODAL",
};
