const screens = {
  HOME: "HOME",
  TAB_ACCOUNT: "TAB_ACCOUNT",
  TAB_NAVIGATE: "TAB_NAVIGATE",
  TAB_NOTIFICATION: "TAB_NOTIFICATION",
  TAB_TASK: "TAB_TASK",
  LOGIN: "LOGIN",
  SIGNUP: "SIGNUP",
  MEMBER_LIST: "MEMBER_LIST",
  MEMBER_DETAIL: "MEMBER_DETAIL",
  MEMBER_RECORD: "MEMBER_RECORD",
  SPINNER: "SPINNER",
  DEPARTMENT_LIST: "DEPARTMENT_LIST",
  DEPARTMENT_DETAIL: "DEPARTMENT_DETAIL",
  DEPARTMENT_RECORD: "DEPARTMENT_RECORD",
};

export default screens;
